### ISSUE TITLE
Cannot inherent `dllistnode`: `RuntimeError: Failed to create string`

### ISSUE THREAD

**Issue by evandrocoan** [ajakubek/python-llist#10]
I subclassed `dllistnode` as follows:
```python
import llist

class LogLine(llist.dllistnode):

    def __init__(self, logline):
        super().__init__( self )
        self.logline = logline

loglist = llist.dllist()
mynode = LogLine( "Full Line!" )

loglist.appendnode( mynode )
string_node = str( mynode )

print( 'mynode', mynode )
print( 'loglist', loglist )
```

And when running it on Python 3, I got this error:
```
evandro@evandro-pc:~/Downloads$ python3 tests.py
Traceback (most recent call last):
  File "/home/evandro/tests.py", line 14, in <module>
    string_node = str( mynode )
RuntimeError: Failed to create string
```

These are my system configurations:
```
evandro@evandro-pc:~/Downloads$ python3 --version
Python 3.6.7

evandro@evandro-pc:~/Downloads$ pip3 show llist
Name: llist
Version: 0.6
Summary: Linked list data structures for Python
Home-page: https://github.com/ajakubek/python-llist
Author: Adam Jakubek, Rafał Gałczyński
Author-email: ajakubek@gmail.com, rafal.galczynski@gmail.com
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: 
```

**Comment by evandrocoan** [comment]
I managed to "make it work" by defining a fake `__str__()`: 
```python
    def __repr__(self):
        return "fake __repr__"

    def __str__(self):
        return self.__repr__()
```

Full example:
```python

import llist

class LogLine(llist.dllistnode):

    def __init__(self, logline):
        super().__init__( self )
        self.logline = logline

    def __repr__(self):
        return "fake __repr__"

    def __str__(self):
        return self.__repr__()

loglist = llist.dllist()
mynode = LogLine( "Full Line!" )

loglist.appendnode( mynode )
string_node = str( mynode )

print( 'mynode', mynode )
print( 'loglist', loglist )
```

**Comment by ajakubek** [comment]
The error is caused by recursive definition of `mynode` in your example.
Consider this simplified snippet:
```
import llist

node = llist.dllistnode()  # create a node
node.value = node          # assign the node as its own value
print(str(node))
```

The default implementation of `str` for `dllistnode` builds the string recursively by calling `str` on the `value` field. This results in an endless loop, since `value` points to its parent.
The `str` function detects this scenario and bails out with an error to prevent a crash.

Now back to your example. In the following line you initialize the parent class of `LogLine` with itself, which creates a similarly "looping" structure:
```
super().__init__( self )
```

Defining a custom `__str__` solved the issue, because it replaced the default formatter (which visits the node value), with a simpler one that returned a constant string.

Alternatively you could initialize the `dllistnode` with `logline` for example, so that `str` would print it by default.
```
super().__init__(logline)
```

Does this solve you issue?

**Comment by evandrocoan** [comment]
I do not think I have an issue. Yes, I do call `super().__init__( self )`, but I never use `node.value` as node itself the my precious value. So, I can either call `super().__init__( logline )` or `super().__init__( self )` and it would not do any difference for my application.

Going even further, either calling `super().__init__( self )` or `super().__init__( logline )` does not affect the memory usage of my application either because internally, both `self` and `logline` are pointers to the actual values of `self` and `logline` respectively.

I just wonder why nodes have to have a value when I am sub-classing them? When I am sub-classing a node, can you allow me to call `super().__init__()`, i.e., without any values? Then, later on when I am calling `node.value` this should return the node itself.

**Comment by ajakubek** [comment]
> When I am sub-classing a node, can you allow me to call `super().__init__()`
You can do that, but `node.value` will be set to `None` in that case.

Anyway, I updated the module to correctly handle lists with cycles between nodes. Your code should work without any further changes.
