### ISSUE TITLE
Implement `insertafter` method in dllist?

### ISSUE THREAD

**Issue by grzaks** [ajakubek/python-llist#14]
Reading the docs I've noticed there is `insertbefore` method in `dllist` but there is no `insertafter`. Is there any rationale for this decision?

Both methods are available in `sllist` class.

**Comment by ajakubek** [comment]
If I remember correctly, the rationale was this:
 1. We wanted to have an interface that matched built-in collections from Python as closely as possible (at least in cases where performance would be acceptable). So we implemented the `dllist.insert(item, before)` method in a way that follows the convention established in `list.insert(item, position)`.  
 2. At the same time we disliked the fact that corresponding `sllist.insert` would be really slow (because `sllistnode` does not have the `prev` pointer and the list would have to be scanned).  
The short `insert` name could incorrectly suggest, that this was the default way of inserting nodes.
In result, we decided to implement two separate methods (`sllist.insertbefore` and `sllist.insertafter`) and document their time complexity.

But then we didn't revisit the `dllist` interface to add the two separate insertion methods.

In the end, you are right that `dllist` should also provide `insertafter` and `insertbefore`. The change would make the type a bit more compatible with `sllist`. For completeness, the structure should also expose `insertnodebefore` and `insertnodeafter`.

I'll schedule these extensions for the next release.

**Comment by ajakubek** [comment]
I implemented the `dllist.insertbefore` and `dllist.insertafter` methods as proposed.
For symmetry I also added `dllist.insertnodebefore` and `dllist.insertnodeafter` (which are based on `dllist.insertnode`).

Changes are currently in master, but I'll probably make a new release this week.
Thanks for the bug report.
