### ISSUE TITLE
Subclassing Nodes

### ISSUE THREAD

**Issue by gitavi** [ajakubek/python-llist#6]
Hi,

I was wondering why the node classes are not subclassable. I'm not that familiar with C so I have no idea about the implications of implementing inheritance, but I'm still curious about why it was designed like this.

Thanks!

**Comment by ajakubek** [comment]
There is no inherent reason why subclassing wasn't supported other than "it's the default behavior for native types in Python". We just didn't think to enable it.

I've just implemented the feature and will push it to master in a moment. I'm going to wait a bit before the 0.6 version is released though. I had to introduce some tricky changes to support cyclic garbage collection (an unrelated issue) and I'd prefer to test it for a while.

**Comment by gitavi** [comment]
Makes sense. I actually went ahead and added the base class flag locally to try it out and it works as expected but appending a subclassed node still unpacks the value attribute and creates a new vanilla node to append to the linked list, so how are allowing for the appending of subclassed nodes?

**Comment by ajakubek** [comment]
Yes, the list will unpack the value from the passed node and put it into a new `dllistnode` or `sllistnode`.

Unfortunately we can't just insert the node from the argument because it may already belong to another list and nodes can have only one owner.
Changing this behavior could break existing code. For example, in the following snippet we would have to throw an exception in the last line to prevent sharing the inserted node between two lists.
```
from llist import dllist

a = dllist([1234])
b = dllist()
b.append(a.first)
```
Currently the code successfully appends the value to `b`, by wrapping it in a new node.
